name: example
description: Example application for the usage of eventbeep_ui plugin

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  ebeep_ui:
    path: ../

flutter:
  uses-material-design: true
  fonts:
    - family: Simple
      fonts:
        - asset: packages/ebeep_ui/fonts/Lato-Regular.ttf
    - family: Heading
      fonts:
        - asset: packages/ebeep_ui/fonts/Poppins-Regular.ttf
    - family: Title
      fonts:
        - asset: packages/ebeep_ui/fonts/JosefinSans-SemiBold.ttf
