name: example
description: Example application for the usage of eventbeep_ui plugin

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"


dependency_overrides:

dependencies:
  flutter:
    sdk: flutter

  ebeep_ui:
    path: ../

flutter:
  fonts:
    - family: EBIcons
      fonts:
        - asset: packages/ebeep_ui/fonts/EBIcons.ttf
    - family: BeepIcons
      fonts:
        - asset: packages/ebeep_ui/fonts/BeepIcons.ttf

  uses-material-design: true
