include: package:effective_dart/analysis_options.yaml

analyzer:
  enable-experiment:
    - extension-methods

  exclude:
    - lib/**/*.gr.dart
    - lib/**/*.iconfig.dart
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart

  errors:
    missing_return: error
    avoid_print: warning
    public_member_api_docs: ignore
    lines_longer_than_80_chars: ignore
    one_member_abstracts: ignore
    todo: ignore
