name: eventbeep_ui
description: An User Interface framework for flutter
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  qr: ^1.2.0
  shimmer: ^1.0.0
  cached_network_image: ^2.0.0-rc
  separated_column: ^1.0.1+2
  flutter_html: ^0.10.4
  url_launcher:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
