name: ebeep_ui
description: An User Interface framework for flutter
version: 0.1.1
author:
homepage:

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  qr: ^1.2.0
  shimmer: ^1.1.1
  cached_network_image: ^2.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  effective_dart: ^1.2.1