name: ebeep_ui
description: An User Interface framework for flutter
version: 0.2.0
author:
homepage:

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  qr: ^2.0.0
  shimmer: ^2.0.0-nullsafety.0
  cached_network_image: ^3.0.0
  flutter_linkify: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  effective_dart: ^1.3.1

flutter:
  fonts:
    - family: EBIcons
      fonts:
        - asset: lib/icons/EBIcons.ttf

  uses-material-design: true
