name: ebeep_ui
description: An User Interface framework for flutter
version: 0.1.1
author:
homepage:

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  auto_size_text: ^3.0.0
  cached_network_image: ^3.0.0
  flutter_linkify: ^5.0.2
  flutter_screenutil: ^5.5.4
  google_fonts: ^2.3.2
  qr: ^2.0.0
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  effective_dart: ^1.3.1

flutter:
  fonts:
    - family: EBIcons
      fonts:
        - asset: lib/icons/EBIcons.ttf
    - family: BeepIcons
      fonts:
        - asset: lib/icons/BeepIcons.ttf
    - family: ClashDisplay
      fonts:
        - asset: lib/fonts/ClashDisplay/ClashDisplay-Bold.otf
          weight: 700
        - asset: lib/fonts/ClashDisplay/ClashDisplay-Semibold.otf
          weight: 600
        - asset: lib/fonts/ClashDisplay/ClashDisplay-Medium.otf
          weight: 500
        - asset: lib/fonts/ClashDisplay/ClashDisplay-Regular.otf
          weight: 400
        - asset: lib/fonts/ClashDisplay/ClashDisplay-Light.otf
          weight: 300
        - asset: lib/fonts/ClashDisplay/ClashDisplay-Extralight.otf
          weight: 200

  uses-material-design: true
