/// Flutter icons AntIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AntIcons
///      fonts:
///       - asset: fonts/AntIcons.ttf
///
///
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
///
import 'package:flutter/widgets.dart';

class AntIcons {
  AntIcons._();

  static const String _kFontFam = 'AntIcons';

  static const IconData sort_alpha_asc =
      IconData(0xe800, fontFamily: _kFontFam);
  static const IconData home = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData apartment = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData pencil = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData magic_wand = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData drop = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData lighter = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData poop = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData sun = IconData(0xe808, fontFamily: _kFontFam);
  static const IconData moon = IconData(0xe809, fontFamily: _kFontFam);
  static const IconData cloud = IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData cloud_upload = IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData cloud_download =
      IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData cloud_sync = IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData cloud_check = IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData database = IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData lock = IconData(0xe810, fontFamily: _kFontFam);
  static const IconData cog = IconData(0xe811, fontFamily: _kFontFam);
  static const IconData trash = IconData(0xe812, fontFamily: _kFontFam);
  static const IconData dice = IconData(0xe813, fontFamily: _kFontFam);
  static const IconData star = IconData(0xe814, fontFamily: _kFontFam);
  static const IconData star_half = IconData(0xe815, fontFamily: _kFontFam);
  static const IconData star_empty = IconData(0xe816, fontFamily: _kFontFam);
  static const IconData flag = IconData(0xe817, fontFamily: _kFontFam);
  static const IconData envelope = IconData(0xe818, fontFamily: _kFontFam);
  static const IconData paperclip = IconData(0xe819, fontFamily: _kFontFam);
  static const IconData inbox = IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData eye = IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData printer = IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData file_empty = IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData file_add = IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData enter = IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData exit = IconData(0xe820, fontFamily: _kFontFam);
  static const IconData graduation_hat =
      IconData(0xe821, fontFamily: _kFontFam);
  static const IconData license = IconData(0xe822, fontFamily: _kFontFam);
  static const IconData music_note = IconData(0xe823, fontFamily: _kFontFam);
  static const IconData film_play = IconData(0xe824, fontFamily: _kFontFam);
  static const IconData camera_video = IconData(0xe825, fontFamily: _kFontFam);
  static const IconData camera = IconData(0xe826, fontFamily: _kFontFam);
  static const IconData picture = IconData(0xe827, fontFamily: _kFontFam);
  static const IconData book = IconData(0xe828, fontFamily: _kFontFam);
  static const IconData bookmark = IconData(0xe829, fontFamily: _kFontFam);
  static const IconData user = IconData(0xe82a, fontFamily: _kFontFam);
  static const IconData users = IconData(0xe82b, fontFamily: _kFontFam);
  static const IconData shirt = IconData(0xe82c, fontFamily: _kFontFam);
  static const IconData store = IconData(0xe82d, fontFamily: _kFontFam);
  static const IconData cart = IconData(0xe82e, fontFamily: _kFontFam);
  static const IconData tag = IconData(0xe82f, fontFamily: _kFontFam);
  static const IconData phone_handset = IconData(0xe830, fontFamily: _kFontFam);
  static const IconData phone = IconData(0xe831, fontFamily: _kFontFam);
  static const IconData pushpin = IconData(0xe832, fontFamily: _kFontFam);
  static const IconData map_marker = IconData(0xe833, fontFamily: _kFontFam);
  static const IconData map = IconData(0xe834, fontFamily: _kFontFam);
  static const IconData location = IconData(0xe835, fontFamily: _kFontFam);
  static const IconData calendar_full = IconData(0xe836, fontFamily: _kFontFam);
  static const IconData keyboard = IconData(0xe837, fontFamily: _kFontFam);
  static const IconData spell_check = IconData(0xe838, fontFamily: _kFontFam);
  static const IconData screen = IconData(0xe839, fontFamily: _kFontFam);
  static const IconData smartphone = IconData(0xe83a, fontFamily: _kFontFam);
  static const IconData tablet = IconData(0xe83b, fontFamily: _kFontFam);
  static const IconData laptop = IconData(0xe83c, fontFamily: _kFontFam);
  static const IconData laptop_phone = IconData(0xe83d, fontFamily: _kFontFam);
  static const IconData power_swtich = IconData(0xe83e, fontFamily: _kFontFam);
  static const IconData lnr_bubble = IconData(0xe83f, fontFamily: _kFontFam);
  static const IconData heart_pulse = IconData(0xe840, fontFamily: _kFontFam);
  static const IconData construction = IconData(0xe841, fontFamily: _kFontFam);
  static const IconData pie_chart = IconData(0xe842, fontFamily: _kFontFam);
  static const IconData chart_bars = IconData(0xe843, fontFamily: _kFontFam);
  static const IconData gift = IconData(0xe844, fontFamily: _kFontFam);
  static const IconData diamond = IconData(0xe845, fontFamily: _kFontFam);
  static const IconData linearicons = IconData(0xe846, fontFamily: _kFontFam);
  static const IconData dinner = IconData(0xe847, fontFamily: _kFontFam);
  static const IconData coffee_cup = IconData(0xe848, fontFamily: _kFontFam);
  static const IconData leaf = IconData(0xe849, fontFamily: _kFontFam);
  static const IconData paw = IconData(0xe84a, fontFamily: _kFontFam);
  static const IconData rocket = IconData(0xe84b, fontFamily: _kFontFam);
  static const IconData briefcase = IconData(0xe84c, fontFamily: _kFontFam);
  static const IconData bus = IconData(0xe84d, fontFamily: _kFontFam);
  static const IconData car = IconData(0xe84e, fontFamily: _kFontFam);
  static const IconData train = IconData(0xe84f, fontFamily: _kFontFam);
  static const IconData bicycle = IconData(0xe850, fontFamily: _kFontFam);
  static const IconData wheelchair = IconData(0xe851, fontFamily: _kFontFam);
  static const IconData select = IconData(0xe852, fontFamily: _kFontFam);
  static const IconData earth = IconData(0xe853, fontFamily: _kFontFam);
  static const IconData smile = IconData(0xe854, fontFamily: _kFontFam);
  static const IconData sad = IconData(0xe855, fontFamily: _kFontFam);
  static const IconData neutral = IconData(0xe856, fontFamily: _kFontFam);
  static const IconData mustache = IconData(0xe857, fontFamily: _kFontFam);
  static const IconData alarm = IconData(0xe858, fontFamily: _kFontFam);
  static const IconData bullhorn = IconData(0xe859, fontFamily: _kFontFam);
  static const IconData volume_high = IconData(0xe85a, fontFamily: _kFontFam);
  static const IconData volume_medium = IconData(0xe85b, fontFamily: _kFontFam);
  static const IconData volume_low = IconData(0xe85c, fontFamily: _kFontFam);
  static const IconData volume = IconData(0xe85d, fontFamily: _kFontFam);
  static const IconData mic = IconData(0xe85e, fontFamily: _kFontFam);
  static const IconData hourglass = IconData(0xe85f, fontFamily: _kFontFam);
  static const IconData undo = IconData(0xe860, fontFamily: _kFontFam);
  static const IconData redo = IconData(0xe861, fontFamily: _kFontFam);
  static const IconData sync_icon = IconData(0xe862, fontFamily: _kFontFam);
  static const IconData history = IconData(0xe863, fontFamily: _kFontFam);
  static const IconData clock = IconData(0xe864, fontFamily: _kFontFam);
  static const IconData download = IconData(0xe865, fontFamily: _kFontFam);
  static const IconData upload = IconData(0xe866, fontFamily: _kFontFam);
  static const IconData enter_down = IconData(0xe867, fontFamily: _kFontFam);
  static const IconData exit_up = IconData(0xe868, fontFamily: _kFontFam);
  static const IconData bug = IconData(0xe869, fontFamily: _kFontFam);
  static const IconData code = IconData(0xe86a, fontFamily: _kFontFam);
  static const IconData link = IconData(0xe86b, fontFamily: _kFontFam);
  static const IconData unlink = IconData(0xe86c, fontFamily: _kFontFam);
  static const IconData thumbs_up = IconData(0xe86d, fontFamily: _kFontFam);
  static const IconData thumbs_down = IconData(0xe86e, fontFamily: _kFontFam);
  static const IconData magnifier = IconData(0xe86f, fontFamily: _kFontFam);
  static const IconData cross = IconData(0xe870, fontFamily: _kFontFam);
  static const IconData menu = IconData(0xe871, fontFamily: _kFontFam);
  static const IconData list = IconData(0xe872, fontFamily: _kFontFam);
  static const IconData chevron_up = IconData(0xe873, fontFamily: _kFontFam);
  static const IconData chevron_down = IconData(0xe874, fontFamily: _kFontFam);
  static const IconData chevron_left = IconData(0xe875, fontFamily: _kFontFam);
  static const IconData chevron_right = IconData(0xe876, fontFamily: _kFontFam);
  static const IconData arrow_up = IconData(0xe877, fontFamily: _kFontFam);
  static const IconData arrow_down = IconData(0xe878, fontFamily: _kFontFam);
  static const IconData arrow_left = IconData(0xe879, fontFamily: _kFontFam);
  static const IconData arrow_right = IconData(0xe87a, fontFamily: _kFontFam);
  static const IconData move = IconData(0xe87b, fontFamily: _kFontFam);
  static const IconData warning = IconData(0xe87c, fontFamily: _kFontFam);
  static const IconData question_circle =
      IconData(0xe87d, fontFamily: _kFontFam);
  static const IconData menu_circle = IconData(0xe87e, fontFamily: _kFontFam);
  static const IconData checkmark_cicle =
      IconData(0xe87f, fontFamily: _kFontFam);
  static const IconData cross_circle = IconData(0xe880, fontFamily: _kFontFam);
  static const IconData plus_circle = IconData(0xe881, fontFamily: _kFontFam);
  static const IconData circle_minus = IconData(0xe882, fontFamily: _kFontFam);
  static const IconData arrow_up_circle =
      IconData(0xe883, fontFamily: _kFontFam);
  static const IconData arrow_down_circle =
      IconData(0xe884, fontFamily: _kFontFam);
  static const IconData arrow_left_circle =
      IconData(0xe885, fontFamily: _kFontFam);
  static const IconData arrow_right_circle =
      IconData(0xe886, fontFamily: _kFontFam);
  static const IconData chevron_up_circle =
      IconData(0xe887, fontFamily: _kFontFam);
  static const IconData chevron_down_circle =
      IconData(0xe888, fontFamily: _kFontFam);
  static const IconData chevron_left_circle =
      IconData(0xe889, fontFamily: _kFontFam);
  static const IconData chevron_right_circle =
      IconData(0xe88a, fontFamily: _kFontFam);
  static const IconData crop = IconData(0xe88b, fontFamily: _kFontFam);
  static const IconData frame_expand = IconData(0xe88c, fontFamily: _kFontFam);
  static const IconData frame_contract =
      IconData(0xe88d, fontFamily: _kFontFam);
  static const IconData layers = IconData(0xe88e, fontFamily: _kFontFam);
  static const IconData funnel = IconData(0xe88f, fontFamily: _kFontFam);
  static const IconData text_format = IconData(0xe890, fontFamily: _kFontFam);
  static const IconData text_format_remove =
      IconData(0xe891, fontFamily: _kFontFam);
  static const IconData text_size = IconData(0xe892, fontFamily: _kFontFam);
  static const IconData bold = IconData(0xe893, fontFamily: _kFontFam);
  static const IconData italic = IconData(0xe894, fontFamily: _kFontFam);
  static const IconData underline = IconData(0xe895, fontFamily: _kFontFam);
  static const IconData strikethrough = IconData(0xe896, fontFamily: _kFontFam);
  static const IconData highlight = IconData(0xe897, fontFamily: _kFontFam);
  static const IconData text_align_left =
      IconData(0xe898, fontFamily: _kFontFam);
  static const IconData text_align_center =
      IconData(0xe899, fontFamily: _kFontFam);
  static const IconData text_align_right =
      IconData(0xe89a, fontFamily: _kFontFam);
  static const IconData text_align_justify =
      IconData(0xe89b, fontFamily: _kFontFam);
  static const IconData line_spacing = IconData(0xe89c, fontFamily: _kFontFam);
  static const IconData indent_increase =
      IconData(0xe89d, fontFamily: _kFontFam);
  static const IconData indent_decrease =
      IconData(0xe89e, fontFamily: _kFontFam);
  static const IconData pilcrow = IconData(0xe89f, fontFamily: _kFontFam);
  static const IconData direction_ltr = IconData(0xe8a0, fontFamily: _kFontFam);
  static const IconData direction_rtl = IconData(0xe8a1, fontFamily: _kFontFam);
  static const IconData page_break = IconData(0xe8a2, fontFamily: _kFontFam);
  static const IconData heart = IconData(0xe8a3, fontFamily: _kFontFam);
  static const IconData sort_amount_asc =
      IconData(0xe8a4, fontFamily: _kFontFam);
  static const IconData hand = IconData(0xe8a5, fontFamily: _kFontFam);
  static const IconData pointer_up = IconData(0xe8a6, fontFamily: _kFontFam);
  static const IconData pointer_right = IconData(0xe8a7, fontFamily: _kFontFam);
  static const IconData pointer_down = IconData(0xe8a8, fontFamily: _kFontFam);
  static const IconData pointer_left = IconData(0xe8a9, fontFamily: _kFontFam);
  static const IconData arrow_left_1 = IconData(0xe8aa, fontFamily: _kFontFam);
  static const IconData arrow_right_1 = IconData(0xe8ab, fontFamily: _kFontFam);
  static const IconData arrows_alt = IconData(0xe8ac, fontFamily: _kFontFam);
  static const IconData arrow_up_1 = IconData(0xe8ad, fontFamily: _kFontFam);
  static const IconData audio = IconData(0xe8ae, fontFamily: _kFontFam);
  static const IconData audit = IconData(0xe8af, fontFamily: _kFontFam);
  static const IconData backward = IconData(0xe8b0, fontFamily: _kFontFam);
  static const IconData bank = IconData(0xe8b1, fontFamily: _kFontFam);
  static const IconData bar_chart = IconData(0xe8b2, fontFamily: _kFontFam);
  static const IconData barcode = IconData(0xe8b3, fontFamily: _kFontFam);
  static const IconData bars = IconData(0xe8b4, fontFamily: _kFontFam);
  static const IconData behance = IconData(0xe8b5, fontFamily: _kFontFam);
  static const IconData behance_square =
      IconData(0xe8b6, fontFamily: _kFontFam);
  static const IconData bell = IconData(0xe8b7, fontFamily: _kFontFam);
  static const IconData bg_colors = IconData(0xe8b8, fontFamily: _kFontFam);
  static const IconData block = IconData(0xe8b9, fontFamily: _kFontFam);
  static const IconData bold_1 = IconData(0xe8ba, fontFamily: _kFontFam);
  static const IconData book_1 = IconData(0xe8bb, fontFamily: _kFontFam);
  static const IconData border = IconData(0xe8bc, fontFamily: _kFontFam);
  static const IconData border_bottom = IconData(0xe8bd, fontFamily: _kFontFam);
  static const IconData border_horizontal =
      IconData(0xe8be, fontFamily: _kFontFam);
  static const IconData border_inner = IconData(0xe8bf, fontFamily: _kFontFam);
  static const IconData border_outer = IconData(0xe8c0, fontFamily: _kFontFam);
  static const IconData border_left = IconData(0xe8c1, fontFamily: _kFontFam);
  static const IconData border_right = IconData(0xe8c2, fontFamily: _kFontFam);
  static const IconData border_top = IconData(0xe8c3, fontFamily: _kFontFam);
  static const IconData border_verticle =
      IconData(0xe8c4, fontFamily: _kFontFam);
  static const IconData box_plot = IconData(0xe8c5, fontFamily: _kFontFam);
  static const IconData branches = IconData(0xe8c6, fontFamily: _kFontFam);
  static const IconData build = IconData(0xe8c7, fontFamily: _kFontFam);
  static const IconData bulb = IconData(0xe8c8, fontFamily: _kFontFam);
  static const IconData calculator = IconData(0xe8c9, fontFamily: _kFontFam);
  static const IconData calendar = IconData(0xe8ca, fontFamily: _kFontFam);
  static const IconData camera_1 = IconData(0xe8cb, fontFamily: _kFontFam);
  static const IconData car_1 = IconData(0xe8cc, fontFamily: _kFontFam);
  static const IconData caret_down = IconData(0xe8cd, fontFamily: _kFontFam);
  static const IconData caret_left = IconData(0xe8ce, fontFamily: _kFontFam);
  static const IconData caret_right = IconData(0xe8cf, fontFamily: _kFontFam);
  static const IconData caret_up = IconData(0xe8d0, fontFamily: _kFontFam);
  static const IconData carry_out = IconData(0xe8d1, fontFamily: _kFontFam);
  static const IconData check = IconData(0xe8d2, fontFamily: _kFontFam);
  static const IconData check_circle = IconData(0xe8d3, fontFamily: _kFontFam);
  static const IconData check_square = IconData(0xe8d4, fontFamily: _kFontFam);
  static const IconData chrome = IconData(0xe8d5, fontFamily: _kFontFam);
  static const IconData ci = IconData(0xe8d6, fontFamily: _kFontFam);
  static const IconData clock_circle = IconData(0xe8d7, fontFamily: _kFontFam);
  static const IconData close = IconData(0xe8d8, fontFamily: _kFontFam);
  static const IconData close_circle = IconData(0xe8d9, fontFamily: _kFontFam);
  static const IconData close_square = IconData(0xe8da, fontFamily: _kFontFam);
  static const IconData cloud_1 = IconData(0xe8db, fontFamily: _kFontFam);
  static const IconData cloud_download_1 =
      IconData(0xe8dc, fontFamily: _kFontFam);
  static const IconData cloud_server = IconData(0xe8dd, fontFamily: _kFontFam);
  static const IconData cloud_sync_1 = IconData(0xe8de, fontFamily: _kFontFam);
  static const IconData cloud_upload_1 =
      IconData(0xe8df, fontFamily: _kFontFam);
  static const IconData cluster = IconData(0xe8e0, fontFamily: _kFontFam);
  static const IconData code_1 = IconData(0xe8e1, fontFamily: _kFontFam);
  static const IconData codepen = IconData(0xe8e2, fontFamily: _kFontFam);
  static const IconData codepen_circle =
      IconData(0xe8e3, fontFamily: _kFontFam);
  static const IconData code_sandbox = IconData(0xe8e4, fontFamily: _kFontFam);
  static const IconData coffee = IconData(0xe8e5, fontFamily: _kFontFam);
  static const IconData colum_height = IconData(0xe8e6, fontFamily: _kFontFam);
  static const IconData column_width = IconData(0xe8e7, fontFamily: _kFontFam);
  static const IconData compass = IconData(0xe8e8, fontFamily: _kFontFam);
  static const IconData contacts = IconData(0xe8e9, fontFamily: _kFontFam);
  static const IconData container = IconData(0xe8ea, fontFamily: _kFontFam);
  static const IconData control = IconData(0xe8eb, fontFamily: _kFontFam);
  static const IconData copy = IconData(0xe8ec, fontFamily: _kFontFam);
  static const IconData copyright = IconData(0xe8ed, fontFamily: _kFontFam);
  static const IconData credit_card = IconData(0xe8ee, fontFamily: _kFontFam);
  static const IconData crown = IconData(0xe8ef, fontFamily: _kFontFam);
  static const IconData customer_service =
      IconData(0xe8f0, fontFamily: _kFontFam);
  static const IconData dashboard = IconData(0xe8f1, fontFamily: _kFontFam);
  static const IconData dash = IconData(0xe8f2, fontFamily: _kFontFam);
  static const IconData database_1 = IconData(0xe8f3, fontFamily: _kFontFam);
  static const IconData delete = IconData(0xe8f4, fontFamily: _kFontFam);
  static const IconData deployment_unit =
      IconData(0xe8f5, fontFamily: _kFontFam);
  static const IconData desktop = IconData(0xe8f6, fontFamily: _kFontFam);
  static const IconData diff = IconData(0xe8f7, fontFamily: _kFontFam);
  static const IconData dingding = IconData(0xe8f8, fontFamily: _kFontFam);
  static const IconData disconnect = IconData(0xe8f9, fontFamily: _kFontFam);
  static const IconData dislike = IconData(0xe8fa, fontFamily: _kFontFam);
  static const IconData dollar = IconData(0xe8fb, fontFamily: _kFontFam);
  static const IconData dot_chart = IconData(0xe8fc, fontFamily: _kFontFam);
  static const IconData double_left = IconData(0xe8fd, fontFamily: _kFontFam);
  static const IconData double_right = IconData(0xe8fe, fontFamily: _kFontFam);
  static const IconData down = IconData(0xe8ff, fontFamily: _kFontFam);
  static const IconData down_circle = IconData(0xe900, fontFamily: _kFontFam);
  static const IconData download_1 = IconData(0xe901, fontFamily: _kFontFam);
  static const IconData down_square = IconData(0xe902, fontFamily: _kFontFam);
  static const IconData drag = IconData(0xe903, fontFamily: _kFontFam);
  static const IconData dribbble = IconData(0xe904, fontFamily: _kFontFam);
  static const IconData dribbble_square =
      IconData(0xe905, fontFamily: _kFontFam);
  static const IconData dropbox = IconData(0xe906, fontFamily: _kFontFam);
  static const IconData edit = IconData(0xe907, fontFamily: _kFontFam);
  static const IconData ellipsis = IconData(0xe908, fontFamily: _kFontFam);
  static const IconData enter_1 = IconData(0xe909, fontFamily: _kFontFam);
  static const IconData environment = IconData(0xe90a, fontFamily: _kFontFam);
  static const IconData euro = IconData(0xe90b, fontFamily: _kFontFam);
  static const IconData exception = IconData(0xe90c, fontFamily: _kFontFam);
  static const IconData exclamation = IconData(0xe90d, fontFamily: _kFontFam);
  static const IconData exclamation_circle =
      IconData(0xe90e, fontFamily: _kFontFam);
  static const IconData experiment = IconData(0xe90f, fontFamily: _kFontFam);
  static const IconData export_icon = IconData(0xe910, fontFamily: _kFontFam);
  static const IconData eye_1 = IconData(0xe911, fontFamily: _kFontFam);
  static const IconData eye_invisible = IconData(0xe912, fontFamily: _kFontFam);
  static const IconData facebook = IconData(0xe913, fontFamily: _kFontFam);
  static const IconData fall = IconData(0xe914, fontFamily: _kFontFam);
  static const IconData fast_backward = IconData(0xe915, fontFamily: _kFontFam);
  static const IconData fast_forward = IconData(0xe916, fontFamily: _kFontFam);
  static const IconData file = IconData(0xe917, fontFamily: _kFontFam);
  static const IconData file_add_1 = IconData(0xe918, fontFamily: _kFontFam);
  static const IconData file_done = IconData(0xe919, fontFamily: _kFontFam);
  static const IconData setting = IconData(0xe91a, fontFamily: _kFontFam);
  static const IconData shake = IconData(0xe91b, fontFamily: _kFontFam);
  static const IconData file_excel = IconData(0xe91c, fontFamily: _kFontFam);
  static const IconData file_exclamation =
      IconData(0xe91d, fontFamily: _kFontFam);
  static const IconData file_image = IconData(0xe91e, fontFamily: _kFontFam);
  static const IconData file_jpg = IconData(0xe91f, fontFamily: _kFontFam);
  static const IconData file_markdown = IconData(0xe920, fontFamily: _kFontFam);
  static const IconData file_pdf = IconData(0xe921, fontFamily: _kFontFam);
  static const IconData file_ppt = IconData(0xe922, fontFamily: _kFontFam);
  static const IconData file_protect = IconData(0xe923, fontFamily: _kFontFam);
  static const IconData file_search = IconData(0xe924, fontFamily: _kFontFam);
  static const IconData file_sync = IconData(0xe925, fontFamily: _kFontFam);
  static const IconData file_text = IconData(0xe926, fontFamily: _kFontFam);
  static const IconData file_unknown = IconData(0xe927, fontFamily: _kFontFam);
  static const IconData file_word = IconData(0xe928, fontFamily: _kFontFam);
  static const IconData file_zip = IconData(0xe929, fontFamily: _kFontFam);
  static const IconData filter = IconData(0xe92a, fontFamily: _kFontFam);
  static const IconData fire = IconData(0xe92b, fontFamily: _kFontFam);
  static const IconData flag_1 = IconData(0xe92c, fontFamily: _kFontFam);
  static const IconData folder = IconData(0xe92d, fontFamily: _kFontFam);
  static const IconData folder_add = IconData(0xe92e, fontFamily: _kFontFam);
  static const IconData folder_open = IconData(0xe92f, fontFamily: _kFontFam);
  static const IconData step_forward = IconData(0xe930, fontFamily: _kFontFam);
  static const IconData stock = IconData(0xe931, fontFamily: _kFontFam);
  static const IconData font_colors = IconData(0xe932, fontFamily: _kFontFam);
  static const IconData font_size = IconData(0xe933, fontFamily: _kFontFam);
  static const IconData fork = IconData(0xe934, fontFamily: _kFontFam);
  static const IconData form = IconData(0xe935, fontFamily: _kFontFam);
  static const IconData forward = IconData(0xe936, fontFamily: _kFontFam);
  static const IconData frown = IconData(0xe937, fontFamily: _kFontFam);
  static const IconData fullscreen = IconData(0xe938, fontFamily: _kFontFam);
  static const IconData fullscreen_exit =
      IconData(0xe939, fontFamily: _kFontFam);
  static const IconData fund = IconData(0xe93a, fontFamily: _kFontFam);
  static const IconData funnel_plot = IconData(0xe93b, fontFamily: _kFontFam);
  static const IconData gateway = IconData(0xe93c, fontFamily: _kFontFam);
  static const IconData gift_1 = IconData(0xe93d, fontFamily: _kFontFam);
  static const IconData github = IconData(0xe93e, fontFamily: _kFontFam);
  static const IconData gitlab = IconData(0xe93f, fontFamily: _kFontFam);
  static const IconData global = IconData(0xe940, fontFamily: _kFontFam);
  static const IconData gold = IconData(0xe941, fontFamily: _kFontFam);
  static const IconData google = IconData(0xe942, fontFamily: _kFontFam);
  static const IconData google_plus = IconData(0xe943, fontFamily: _kFontFam);
  static const IconData transaction = IconData(0xe944, fontFamily: _kFontFam);
  static const IconData trophy = IconData(0xe945, fontFamily: _kFontFam);
  static const IconData hdd = IconData(0xe946, fontFamily: _kFontFam);
  static const IconData heart_1 = IconData(0xe947, fontFamily: _kFontFam);
  static const IconData heat_map = IconData(0xe948, fontFamily: _kFontFam);
  static const IconData highlight_1 = IconData(0xe949, fontFamily: _kFontFam);
  static const IconData history_1 = IconData(0xe94a, fontFamily: _kFontFam);
  static const IconData home_1 = IconData(0xe94b, fontFamily: _kFontFam);
  static const IconData hourglass_1 = IconData(0xe94c, fontFamily: _kFontFam);
  static const IconData html5 = IconData(0xe94d, fontFamily: _kFontFam);
  static const IconData idcard = IconData(0xe94e, fontFamily: _kFontFam);
  static const IconData ie = IconData(0xe94f, fontFamily: _kFontFam);
  static const IconData import_icon = IconData(0xe950, fontFamily: _kFontFam);
  static const IconData inbox_1 = IconData(0xe951, fontFamily: _kFontFam);
  static const IconData info = IconData(0xe952, fontFamily: _kFontFam);
  static const IconData info_circle = IconData(0xe953, fontFamily: _kFontFam);
  static const IconData instagram = IconData(0xe954, fontFamily: _kFontFam);
  static const IconData insurance = IconData(0xe955, fontFamily: _kFontFam);
  static const IconData interation = IconData(0xe956, fontFamily: _kFontFam);
  static const IconData issues_close = IconData(0xe957, fontFamily: _kFontFam);
  static const IconData vertical_left = IconData(0xe958, fontFamily: _kFontFam);
  static const IconData vertical_right =
      IconData(0xe959, fontFamily: _kFontFam);
  static const IconData italic_1 = IconData(0xe95a, fontFamily: _kFontFam);
  static const IconData key = IconData(0xe95b, fontFamily: _kFontFam);
  static const IconData laptop_1 = IconData(0xe95c, fontFamily: _kFontFam);
  static const IconData layout = IconData(0xe95d, fontFamily: _kFontFam);
  static const IconData left = IconData(0xe95e, fontFamily: _kFontFam);
  static const IconData left_circle = IconData(0xe95f, fontFamily: _kFontFam);
  static const IconData left_square = IconData(0xe960, fontFamily: _kFontFam);
  static const IconData like = IconData(0xe961, fontFamily: _kFontFam);
  static const IconData line = IconData(0xe962, fontFamily: _kFontFam);
  static const IconData line_chart = IconData(0xe963, fontFamily: _kFontFam);
  static const IconData line_height = IconData(0xe964, fontFamily: _kFontFam);
  static const IconData link_1 = IconData(0xe965, fontFamily: _kFontFam);
  static const IconData linkedin = IconData(0xe966, fontFamily: _kFontFam);
  static const IconData loading = IconData(0xe967, fontFamily: _kFontFam);
  static const IconData loading_3_quarters =
      IconData(0xe968, fontFamily: _kFontFam);
  static const IconData lock_1 = IconData(0xe969, fontFamily: _kFontFam);
  static const IconData login = IconData(0xe96a, fontFamily: _kFontFam);
  static const IconData logout = IconData(0xe96b, fontFamily: _kFontFam);
  static const IconData mail = IconData(0xe96c, fontFamily: _kFontFam);
  static const IconData man = IconData(0xe96d, fontFamily: _kFontFam);
  static const IconData medicine_box = IconData(0xe96e, fontFamily: _kFontFam);
  static const IconData medium = IconData(0xe96f, fontFamily: _kFontFam);
  static const IconData medium_workmark =
      IconData(0xe970, fontFamily: _kFontFam);
  static const IconData meh = IconData(0xe971, fontFamily: _kFontFam);
  static const IconData menu_1 = IconData(0xe972, fontFamily: _kFontFam);
  static const IconData menu_fold = IconData(0xe973, fontFamily: _kFontFam);
  static const IconData menu_unfold = IconData(0xe974, fontFamily: _kFontFam);
  static const IconData message = IconData(0xe975, fontFamily: _kFontFam);
  static const IconData minus = IconData(0xe976, fontFamily: _kFontFam);
  static const IconData minus_circle = IconData(0xe977, fontFamily: _kFontFam);
  static const IconData minus_square = IconData(0xe978, fontFamily: _kFontFam);
  static const IconData mobile = IconData(0xe979, fontFamily: _kFontFam);
  static const IconData money_collect = IconData(0xe97a, fontFamily: _kFontFam);
  static const IconData monitor = IconData(0xe97b, fontFamily: _kFontFam);
  static const IconData account_book = IconData(0xe97c, fontFamily: _kFontFam);
  static const IconData notification = IconData(0xe97d, fontFamily: _kFontFam);
  static const IconData number = IconData(0xe97e, fontFamily: _kFontFam);
  static const IconData ordered_list = IconData(0xe97f, fontFamily: _kFontFam);
  static const IconData paper_clip = IconData(0xe980, fontFamily: _kFontFam);
  static const IconData pause = IconData(0xe981, fontFamily: _kFontFam);
  static const IconData pause_circle = IconData(0xe982, fontFamily: _kFontFam);
  static const IconData pay_circle = IconData(0xe983, fontFamily: _kFontFam);
  static const IconData percentage = IconData(0xe984, fontFamily: _kFontFam);
  static const IconData phone_1 = IconData(0xe985, fontFamily: _kFontFam);
  static const IconData pic_center = IconData(0xe986, fontFamily: _kFontFam);
  static const IconData pic_left = IconData(0xe987, fontFamily: _kFontFam);
  static const IconData pic_right = IconData(0xe988, fontFamily: _kFontFam);
  static const IconData picture_1 = IconData(0xe989, fontFamily: _kFontFam);
  static const IconData pie_chart_1 = IconData(0xe98a, fontFamily: _kFontFam);
  static const IconData play_circle = IconData(0xe98b, fontFamily: _kFontFam);
  static const IconData play_square = IconData(0xe98c, fontFamily: _kFontFam);
  static const IconData plus = IconData(0xe98d, fontFamily: _kFontFam);
  static const IconData plus_circle_1 = IconData(0xe98e, fontFamily: _kFontFam);
  static const IconData plus_square = IconData(0xe98f, fontFamily: _kFontFam);
  static const IconData pound = IconData(0xe990, fontFamily: _kFontFam);
  static const IconData poweroff = IconData(0xe991, fontFamily: _kFontFam);
  static const IconData printer_1 = IconData(0xe992, fontFamily: _kFontFam);
  static const IconData profile = IconData(0xe993, fontFamily: _kFontFam);
  static const IconData project = IconData(0xe994, fontFamily: _kFontFam);
  static const IconData property_safety =
      IconData(0xe995, fontFamily: _kFontFam);
  static const IconData pull_request = IconData(0xe996, fontFamily: _kFontFam);
  static const IconData pushpin_1 = IconData(0xe997, fontFamily: _kFontFam);
  static const IconData qq = IconData(0xe998, fontFamily: _kFontFam);
  static const IconData qrcode = IconData(0xe999, fontFamily: _kFontFam);
  static const IconData question = IconData(0xe99a, fontFamily: _kFontFam);
  static const IconData question_circle_1 =
      IconData(0xe99b, fontFamily: _kFontFam);
  static const IconData radar_chart = IconData(0xe99c, fontFamily: _kFontFam);
  static const IconData radius_bottomleft =
      IconData(0xe99d, fontFamily: _kFontFam);
  static const IconData radius_bottomright =
      IconData(0xe99e, fontFamily: _kFontFam);
  static const IconData radius_setting =
      IconData(0xe99f, fontFamily: _kFontFam);
  static const IconData radius_upleft = IconData(0xe9a0, fontFamily: _kFontFam);
  static const IconData radius_upright =
      IconData(0xe9a1, fontFamily: _kFontFam);
  static const IconData read = IconData(0xe9a2, fontFamily: _kFontFam);
  static const IconData reconciliation =
      IconData(0xe9a3, fontFamily: _kFontFam);
  static const IconData reddit = IconData(0xe9a4, fontFamily: _kFontFam);
  static const IconData red_envelope = IconData(0xe9a5, fontFamily: _kFontFam);
  static const IconData redo_1 = IconData(0xe9a6, fontFamily: _kFontFam);
  static const IconData reload = IconData(0xe9a7, fontFamily: _kFontFam);
  static const IconData rest = IconData(0xe9a8, fontFamily: _kFontFam);
  static const IconData retweet = IconData(0xe9a9, fontFamily: _kFontFam);
  static const IconData right = IconData(0xe9aa, fontFamily: _kFontFam);
  static const IconData right_circle = IconData(0xe9ab, fontFamily: _kFontFam);
  static const IconData right_square = IconData(0xe9ac, fontFamily: _kFontFam);
  static const IconData rise = IconData(0xe9ad, fontFamily: _kFontFam);
  static const IconData robot = IconData(0xe9ae, fontFamily: _kFontFam);
  static const IconData rocket_1 = IconData(0xe9af, fontFamily: _kFontFam);
  static const IconData rollback = IconData(0xe9b0, fontFamily: _kFontFam);
  static const IconData safety = IconData(0xe9b1, fontFamily: _kFontFam);
  static const IconData safety_certificate =
      IconData(0xe9b2, fontFamily: _kFontFam);
  static const IconData save = IconData(0xe9b3, fontFamily: _kFontFam);
  static const IconData scan = IconData(0xe9b4, fontFamily: _kFontFam);
  static const IconData schedule = IconData(0xe9b5, fontFamily: _kFontFam);
  static const IconData scissor = IconData(0xe9b6, fontFamily: _kFontFam);
  static const IconData search = IconData(0xe9b7, fontFamily: _kFontFam);
  static const IconData share_alt = IconData(0xe9b8, fontFamily: _kFontFam);
  static const IconData shop = IconData(0xe9b9, fontFamily: _kFontFam);
  static const IconData shopping = IconData(0xe9ba, fontFamily: _kFontFam);
  static const IconData shopping_cart = IconData(0xe9bb, fontFamily: _kFontFam);
  static const IconData shrink = IconData(0xe9bc, fontFamily: _kFontFam);
  static const IconData sketch = IconData(0xe9bd, fontFamily: _kFontFam);
  static const IconData skin = IconData(0xe9be, fontFamily: _kFontFam);
  static const IconData skype = IconData(0xe9bf, fontFamily: _kFontFam);
  static const IconData sliders = IconData(0xe9c0, fontFamily: _kFontFam);
  static const IconData small_dash = IconData(0xe9c1, fontFamily: _kFontFam);
  static const IconData smile_1 = IconData(0xe9c2, fontFamily: _kFontFam);
  static const IconData snippets = IconData(0xe9c3, fontFamily: _kFontFam);
  static const IconData solution = IconData(0xe9c4, fontFamily: _kFontFam);
  static const IconData sort_ascending =
      IconData(0xe9c5, fontFamily: _kFontFam);
  static const IconData sort_descending =
      IconData(0xe9c6, fontFamily: _kFontFam);
  static const IconData sound = IconData(0xe9c7, fontFamily: _kFontFam);
  static const IconData stop = IconData(0xe9c8, fontFamily: _kFontFam);
  static const IconData strikethrough_1 =
      IconData(0xe9c9, fontFamily: _kFontFam);
  static const IconData swap = IconData(0xe9ca, fontFamily: _kFontFam);
  static const IconData swap_left = IconData(0xe9cb, fontFamily: _kFontFam);
  static const IconData swap_right = IconData(0xe9cc, fontFamily: _kFontFam);
  static const IconData switcher = IconData(0xe9cd, fontFamily: _kFontFam);
  static const IconData sync_1 = IconData(0xe9ce, fontFamily: _kFontFam);
  static const IconData table = IconData(0xe9cf, fontFamily: _kFontFam);
  static const IconData tablet_1 = IconData(0xe9d0, fontFamily: _kFontFam);
  static const IconData tag_1 = IconData(0xe9d1, fontFamily: _kFontFam);
  static const IconData tags = IconData(0xe9d2, fontFamily: _kFontFam);
  static const IconData alert = IconData(0xe9d3, fontFamily: _kFontFam);
  static const IconData alibaba = IconData(0xe9d4, fontFamily: _kFontFam);
  static const IconData team = IconData(0xe9d5, fontFamily: _kFontFam);
  static const IconData thunderbolt = IconData(0xe9d6, fontFamily: _kFontFam);
  static const IconData tool = IconData(0xe9d7, fontFamily: _kFontFam);
  static const IconData twitter = IconData(0xe9d8, fontFamily: _kFontFam);
  static const IconData underline_1 = IconData(0xe9d9, fontFamily: _kFontFam);
  static const IconData undo_1 = IconData(0xe9da, fontFamily: _kFontFam);
  static const IconData unlock = IconData(0xe9db, fontFamily: _kFontFam);
  static const IconData unordered_list =
      IconData(0xe9dc, fontFamily: _kFontFam);
  static const IconData up = IconData(0xe9dd, fontFamily: _kFontFam);
  static const IconData up_circle = IconData(0xe9de, fontFamily: _kFontFam);
  static const IconData upload_1 = IconData(0xe9df, fontFamily: _kFontFam);
  static const IconData up_square = IconData(0xe9e0, fontFamily: _kFontFam);
  static const IconData usb = IconData(0xe9e1, fontFamily: _kFontFam);
  static const IconData user_1 = IconData(0xe9e2, fontFamily: _kFontFam);
  static const IconData user_add = IconData(0xe9e3, fontFamily: _kFontFam);
  static const IconData user_delete = IconData(0xe9e4, fontFamily: _kFontFam);
  static const IconData usergroup_add = IconData(0xe9e5, fontFamily: _kFontFam);
  static const IconData usergroup_delete =
      IconData(0xe9e6, fontFamily: _kFontFam);
  static const IconData vertical_align_bottom =
      IconData(0xe9e7, fontFamily: _kFontFam);
  static const IconData video_camera = IconData(0xe9e8, fontFamily: _kFontFam);
  static const IconData wallet = IconData(0xe9e9, fontFamily: _kFontFam);
  static const IconData warning_1 = IconData(0xe9ea, fontFamily: _kFontFam);
  static const IconData wechat = IconData(0xe9eb, fontFamily: _kFontFam);
  static const IconData weibo = IconData(0xe9ec, fontFamily: _kFontFam);
  static const IconData weibo_circle = IconData(0xe9ed, fontFamily: _kFontFam);
  static const IconData weibo_square = IconData(0xe9ee, fontFamily: _kFontFam);
  static const IconData wifi = IconData(0xe9ef, fontFamily: _kFontFam);
  static const IconData windows = IconData(0xe9f0, fontFamily: _kFontFam);
  static const IconData woman = IconData(0xe9f1, fontFamily: _kFontFam);
  static const IconData yahoo = IconData(0xe9f2, fontFamily: _kFontFam);
  static const IconData youtube = IconData(0xe9f3, fontFamily: _kFontFam);
  static const IconData yuque = IconData(0xe9f4, fontFamily: _kFontFam);
  static const IconData zhihu = IconData(0xe9f5, fontFamily: _kFontFam);
  static const IconData zoom_in = IconData(0xe9f6, fontFamily: _kFontFam);
  static const IconData zoom_out = IconData(0xe9f7, fontFamily: _kFontFam);
  static const IconData vertical_align_top =
      IconData(0xe9f8, fontFamily: _kFontFam);
  static const IconData vertical_align_middle =
      IconData(0xe9f9, fontFamily: _kFontFam);
  static const IconData star_1 = IconData(0xe9fa, fontFamily: _kFontFam);
  static const IconData to_top = IconData(0xe9fb, fontFamily: _kFontFam);
  static const IconData trademark = IconData(0xe9fc, fontFamily: _kFontFam);
  static const IconData step_backward = IconData(0xe9fd, fontFamily: _kFontFam);
  static const IconData select_1 = IconData(0xe9fe, fontFamily: _kFontFam);
  static const IconData security_scan = IconData(0xe9ff, fontFamily: _kFontFam);
  static const IconData align_center = IconData(0xea00, fontFamily: _kFontFam);
  static const IconData align_left = IconData(0xea01, fontFamily: _kFontFam);
  static const IconData align_right = IconData(0xea02, fontFamily: _kFontFam);
  static const IconData alipay = IconData(0xea03, fontFamily: _kFontFam);
  static const IconData alipay_circle = IconData(0xea04, fontFamily: _kFontFam);
  static const IconData aliwangwang = IconData(0xea05, fontFamily: _kFontFam);
  static const IconData aliyun = IconData(0xea06, fontFamily: _kFontFam);
  static const IconData amazon = IconData(0xea07, fontFamily: _kFontFam);
  static const IconData android = IconData(0xea08, fontFamily: _kFontFam);
  static const IconData ant_cloud = IconData(0xea09, fontFamily: _kFontFam);
  static const IconData ant_design = IconData(0xea0a, fontFamily: _kFontFam);
  static const IconData apartment_1 = IconData(0xea0b, fontFamily: _kFontFam);
  static const IconData api = IconData(0xea0c, fontFamily: _kFontFam);
  static const IconData apple = IconData(0xea0d, fontFamily: _kFontFam);
  static const IconData appstore = IconData(0xea0e, fontFamily: _kFontFam);
  static const IconData area_chart = IconData(0xea0f, fontFamily: _kFontFam);
  static const IconData arrow_down_1 = IconData(0xea10, fontFamily: _kFontFam);
}
