/// Flutter icons BeepIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BeepIcons
///      fonts:
///       - asset: fonts/BeepIcons.ttf
///
/// 
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
///
import 'package:flutter/widgets.dart';

class BeepIcons {
  BeepIcons._();

  static const _kFontFam = 'BeepIcons';
  static const String? _kFontPkg = null;

  static const IconData arroba = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attachment = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell_filled = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bin = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checkmark_circle = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checkmark = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData degree = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_filled = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hyperlink = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mic_filled = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mic = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paper_plane = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reply = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reward_filled = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reward = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData speech_bubble = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData speech_bubbles = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_single = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData users = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData visible_off = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData visible = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu_dots = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mic_off_filled = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData smiley = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hourglass = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData question = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trophy = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData downvote = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_down_circle = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_filled = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share_filled = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back_arrow = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unpin = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clipboard = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData images = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData information = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_image = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upvote = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pushpin = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData external_link = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upload = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blocks_filled = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit_line = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close_circle = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera_plus = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upload_alt = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_circle = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencil = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blocks = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData refer = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flag = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_circle_filled = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close_circle_filled = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData members = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData image_single = IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_video = IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData instagram = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedin = IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData verified_filled = IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark = IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData copy = IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message_share = IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message_plus = IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet = IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beep = IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video_off = IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video_on = IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData screen_share = IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flip_camera = IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flash_off_filled = IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flash_on_filled = IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData capture_image = IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData users_filled = IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData presenter = IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
