/// Flutter icons SymBeepIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SymBeepIcons
///      fonts:
///       - asset: fonts/SymBeepIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SymBeepIcons {
  SymBeepIcons._();

  static const _kFontFam = 'SymBeepIcons';
  static const String? _kFontPkg = null;

  static const IconData add_image = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_user = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell_filled = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData block_user = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData block = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData downvote_filled = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData downvote = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flag = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_filled = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData information = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData leaderboard_filled = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData leaderboard = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_options = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencil = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upvote_filled = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upvote = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
